input_files_data: [
  "/data3/fmazzasc/hyp_run_3/pp2024/custom/cbt/AO2D.root",
  "/data3/fmazzasc/hyp_run_3/pp2025/ah/AO2D.root",
  "/data3/fmazzasc/hyp_run_3/pp2025/ac/AO2D.root",
  "/data3/fmazzasc/hyp_run_3/pp2025/ai/AO2D.root",
  "/data3/fmazzasc/hyp_run_3/pp2025/am/AO2D.root"
]
input_files_mc_h3l: ["/data3/fmazzasc/hyp_run_3/mc/LHC24i5/AO2D_h3l.root"]
input_files_mc_h4l: ["/data3/fmazzasc/hyp_run_3/mc/LHC24i5/AO2D_h4l.root"]

output_dir: "/home/fmazzasc/alice/h4l_pp/results"
output_file: "comb_fit_h4l_pp_2425_rdf.root"

selection: {
  "fPt": "fPt > 1. and fPt < 4",
  "fCosPA": "fCosPA > 0.995",
  "fDcaHe": "abs(fDcaHe) > 0.01",
  "fTPCmomHe": "fTPCmomHe > 0.5",
  "fAvgClSizeCosLambda": "fAvgClSizeCosLambda > 5"
}

pid_selection: {
  "fNSigmaHe4": "fNSigmaHe4 > -2 and fNSigmaHe4 < 4"
}

colliding_system: "pp"
is_matter: "antimatter"
calibrate_he_momentum: False
